# rule identifiers to exclude from running
disabled_rules:
  - trailing_whitespace
  - identifier_name
  - force_unwrapping
  - force_cast

# some rules are only opt-in
opt_in_rules:
  - force_unwrapping

# paths to include during linting. `--path` is ignored if present.
included: 
  - eHatid
  - eHatidTests

# paths to ignore during linting. Takes precedence over `included`.
excluded:
  - Pods